export const STRINGS = {
  appName: 'CoPortal',
  appSubtitle: 'Corporate & Government HR Portal',

  // Auth Screens
  loginTitle: 'Welcome Back',
  loginSubtitle: 'Sign in to access your HR workspace',
  loginBtn: 'Sign In',
  registerCompanyBtn: 'Register Company',
  registerEmployeeBtn: 'Register Employee',
  noAccountYet: "Don't have an account?",
  alreadyHaveAccount: 'Already have an account?',
  registerAsCompany: 'Register as Company Owner',
  registerAsEmployee: 'Register as Employee',
  companyIdLabel: 'Company ID',
  companyIdPlaceholder: 'Enter Company ID (e.g. CO-101)',
  companyNameLabel: 'Company Name',
  companyNamePlaceholder: 'Enter Company Name',
  emailLabel: 'Email Address',
  emailPlaceholder: 'Enter email (e.g. john@company.com)',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  fullNameLabel: 'Full Name',
  fullNamePlaceholder: 'Enter your full name',
  selectRole: 'Select Your Role',

  // Dashboard / Home
  dashboardTitle: 'Dashboard',
  welcomeBack: 'Welcome back,',
  adminBadge: 'Company Owner',
  employeeBadge: 'Employee',
  activeEmployees: 'Active Employees',
  companyCodeText: 'Workspace ID:',
  onboardedSuccess: 'Employee onboarded successfully!',

  // Quick Actions / Widgets
  clockInBtn: 'Clock In',
  clockOutBtn: 'Clock Out',
  todayStatus: 'Today\'s Attendance',
  leavesRemaining: 'Leaves Left',
  upcomingHoliday: 'Next Holiday',
  announcementsFeed: 'Noticeboard',
  viewAll: 'View All',
  noAnnouncements: 'No company announcements yet.',

  // Attendance Screen
  attendanceTitle: 'Attendance Log',
  checkInSuccess: 'Checked in successfully at ',
  checkOutSuccess: 'Checked out successfully at ',
  totalHoursThisWeek: 'Hours Logged This Week',
  workingHoursTrend: 'Working Hours Trend',
  calendarHeading: 'Monthly Tracker',
  present: 'Present',
  absent: 'Absent',
  leave: 'On Leave',
  holiday: 'Holiday',
  elapsedTime: 'Shift Duration',
  notCheckedIn: 'Not checked in yet',

  // Leave Screen
  leaveTitle: 'Leave Console',
  applyLeaveTitle: 'Apply for Leave',
  leaveTypeLabel: 'Leave Type',
  casualLeave: 'Casual Leave',
  sickLeave: 'Sick/Medical Leave',
  earnedLeave: 'Earned/Paid Leave',
  startDateLabel: 'Start Date',
  endDateLabel: 'End Date',
  reasonLabel: 'Reason',
  reasonPlaceholder: 'Why are you applying for leave?',
  submitLeaveBtn: 'Submit Application',
  leaveHistoryTitle: 'Leave History',
  pendingStatus: 'Pending Approval',
  approvedStatus: 'Approved',
  rejectedStatus: 'Rejected',
  leaveBalanceText: 'Leave Balance',
  leaveAppliedSuccess: 'Leave applied successfully!',
  insufficientBalance: 'Insufficient leave balance!',

  // Announcements Screen
  announcementsTitle: 'Broadcasts',
  postAnnouncementTitle: 'Publish New Announcement',
  announcementTextPlaceholder: 'Enter announcement title or content...',
  postBtn: 'Broadcast Message',
  broadcasterLabel: 'Posted by Management',
  emptyBroadcastText: 'Enter some text before publishing.',

  // Performance Screen
  performanceTitle: 'Performance Analytics',
  performanceScore: 'Productivity Score',
  averageHoursText: 'Avg Hours / Day',
  taskCompletionText: 'Task Completion',
  managerFeedbackTitle: 'Manager Review & Feedback',
  noFeedbackText: 'No feedback submitted for this cycle.',
  comparisonTitle: 'Department Benchmarks',
  highPerformer: 'Top Performer',
  needsImprovement: 'Needs Attention',
  satisfactory: 'On Target',

  // Field Force Screen
  fieldForceTitle: 'Field Force Tracker',
  gpsStatus: 'GPS Checkpoint Status',
  gpsConnected: 'GPS Active - Location Acquired',
  checkPointPlaceholder: 'Select Checkpoint / Site Location',
  logCheckpointBtn: 'Log Site Attendance',
  recentLogsTitle: 'Field Checkpoint History',
  checkpointLogged: 'Checkpoint logged successfully!',

  // Messages / Validation
  requiredError: 'This field is required.',
  invalidEmail: 'Please enter a valid email.',
  passwordLengthError: 'Password must be at least 6 characters.',
  authFailed: 'Invalid credentials. Please try again.',
  companyNotFound: 'Company ID not found. Register your company first.'
};
